### ISSUE TITLE
jQuery.fn.bind() and jQuery.fn.unbind() are deprecated

### ISSUE THREAD

**Issue by techouse** [olsonpm/fancybox#2]
Hey! Love your plugin, but jQuery 3.x deprecated .bind() and .unbind() in favor of .on(). Could you please facelift the plugin to comply with jQuery 3.x without using the jQuery migrate JS?

**Comment by olsonpm** [comment]
I'm assuming you found the plugin via `npm`, which I'm glad it was useful for you.  However keep in mind I only exposed the fancyapps' [fancybox](https://github.com/fancyapps/fancyBox) plugin via npm, and issues like the one you describe likely belong there.  Mind seeing if this is something that was fixed by them, and just hasn't been pulled in by my repo?  My repo is fairly dated - but I can update it if people would find that useful.

**Comment by olsonpm** [comment]
Feel free to re-open if my above comment doesn't resolve your issue.
