### ISSUE TITLE
NPM ownership transfer

### ISSUE THREAD

**Issue by jtojnar** [olsonpm/fancybox#3]
Since this repo is no longer updated, could you transfer the npm package `fancybox` to the owner of @fancyapps, janis?

```shell
npm owner add janis fancybox
```

The [scoped package](https://www.npmjs.com/package/@fancyapps/fancybox) is troublesome because it is not supported on Debian’s version of NPM.

**Comment by olsonpm** [comment]
I spoke with the owner of fancyapps over email - his concern was needing to bump up the version of his fancybox repo up one major revision past mine - which would be necessary in the transfer in order not to cause issues with current consumers.

If he changes his mind, I'll definitely give him the repo.  I'll also take pull requests to update this repo.

**Comment by jtojnar** [comment]
It does not look like fancybox uses semver, looking into the change log the version numbers seem pretty much arbitrary. With this in mind, why would not be publishing a 3.1 (released a week ago) fine?

**Comment by olsonpm** [comment]
It doesn't matter whether fancybox supports semver, it matters that npm does.  All consumers of npm's fancybox (my repo) are given the assumption that a major revision means incompatible changes.  Any reinstall of this package will update to the new 3.1, since the version of my package is `"version": "3.0.0",`.  This could break apps, and the only solution is for the owner to update his repo to version 4 upon the transition of ownership.

**Comment by fancyapps** [comment]
fancyBox follows `generation.major.minor` format, therefore I really do not want to bump to v4 just because of this issue. 

While I admire @olsonpm caring about users and strict submission to semver rules, I do not understand why he chooses to continue to mislead anyone who downloads his package.

**Comment by olsonpm** [comment]
@fancyapps - it is part of the npm process for transfer of ownership to make sure applications don't break.  If you feel I'm incorrect, feel free to talk with the npm folk, they can override my decision.
